#!/bin/env bash
import setMsgboxSize
import setMenuSize
import logMessage
import TUISoftware
import Download

TitleText="${core}-部署"
ApiPath="$MCSSHOME/core/BDS/version_manifest.json"

if ($(TUISoftware) --title "${TitleText}"  \
--yes-button "稳定版" \
--no-button "预览版" \
--yesno "请选择您将要部署的${core}版本类型" \
$(setMsgboxSize))
then
  VersionType="release"
else
  VersionType="preview"
fi

log.info "正在获取 [${VersionType}] 版本数据"
VersionData=$(cat "${ApiPath}" | jq -r ".version[] | select(.type == \"$VersionType\") | .id")
unset Options i
for i in ${VersionData[@]}
do
  Options="${i} BDS ${Options}"
done

version=$($(TUISoftware) \
--title "${TitleText}" --menu "请选择${core}版本" \
$(setMenuSize) \
${Options} \
3>&1 1>&2 2>&3)

if [ -z ${version} ]
then
  exit 2
fi

log.info "正在获取 [${version}] 下载链接"
ZipURL=$(cat "${ApiPath}" | jq -r ".version[] | select(.id == \"$version\") | .url.linux")

log.info 开始下载 server.zip
Download server.zip ${ZipURL}

log.info "正在解压 server.zip"
if 7z x server.zip
then
  rm server.zip
else
  rm server.zip
  exit 1
fi

if ($(TUISoftware) --title "${TitleText}"  \
--yes-button "保持默认" \
--no-button "确认修改" \
--yesno "将使用默认服务器配置\n请问是否修改?" \
$(setMsgboxSize))
then
  IHS=1024M
  MHS=2048M
  FRPC=None
  AutoStart=false
  SendEmail=None
else
  $(setServerConfig)
fi

cat > config.json <<FOX
{
  "core": "${core}",
  "version": "${version}",
  "StartName": "${StartName}",
  "IHS": "${IHS}",
  "MHS": "${MHS}",
  "StartCommand": "./bedrock_server",
  "FRPC": "${FRPC}",
  "AutoStart": "${AutoStart}",
  "SendEmail": "${SendEmail}"
}
FOX

log.info 部署完成
