#!/bin/env bash
function Arch(){
if [ -z $1 ]
then
  case $(uname -m) in
  arm64|aarch64)
    echo arm64
    ;;
  amd64|x86_64)
    echo amd64
    ;;
  esac
else
  case $1 in 
  Java)
    case $(uname -m) in
    arm64|aarch64)
      echo aarch64
      ;;
    amd64|x86_64)
      echo x64
      ;;
    esac
  ;;
  esac
fi
}