#!/bin/env bash
import increCounter
import errorReturn
function getData(){
  until curl "$1"
  do
    if IncreCounter
    then
      log.warn "数据获取失败 重试中"
    else
      log.error "数据无法获取 请检查"
      errorReturn
    fi
    sleep 3s
  done
}