#!/bin/env bash
function manageSession(){
case "$1" in
tmux)
  case "$2" in
    start)
      tmux new -s "$3" -d "$4" > /dev/null
      return $?
    ;;
    stop)
      tmux kill-session -t "$3" > /dev/null
      return $?
    ;;
    restart)
      tmux kill-session -t "$3" > /dev/null && tmux new -s "$3" -d "$4" > /dev/null
      return $?
    ;;
    log)
      tmux attach -t "$3" > /dev/null
      return $?
    ;;
    list)
      tmux ls | grep -q "$3"
      return $?
    ;;
    command)
      tmux send-keys -t "$3":0 "$4" Enter > /dev/null
      return $?
    ;;
  esac
;;
screen)
  case "$2" in
    start)
      screen -S "$3" -d -m bash -c "$4" > /dev/null
      return $?
    ;;
    stop)
      Session=$(screen -ls | grep "$3" | awk '{print $1}')
      screen -X -S ${Session} quit > /dev/null
      return $?
    ;;
    restart)
      Session=$(screen -ls | grep "$3" | head -n 1 | awk '{print $1}')
      screen -X -S ${Session} quit && screen -S ${Session} -d -m bash -c "$4" > /dev/null
      return $?
    ;;
    log)
      Session=$(screen -ls | grep "$3" | awk '{print $1}')
      screen -r ${Session} > /dev/null
      return $?
    ;;
    list)
      screen -ls | grep -q "$3"
      return $?
    ;;
    command)
      screen -S "$3" -X stuff "$4\n" > /dev/null
      return $?
    ;;
  esac
;;
esac
}